- src/store/actions.js
- src/store/loginStore.js
- fixes data fetching from login endpoint
> fix: data login from fetch

- package-lock.json
- package.json
- src/App.js
- src/Pages/Rooms/index.jsx
- src/components/MainNav/index.jsx
- src/components/RoomCard/RoomCard.jsx
- src/components/RoomCard/RoomCard.module.scss
- src/libs/variables.scss
Questa PR:
- add RoomCard component with style
- add RoomCard to page Rooms
- add some variables to libs/variables.scss
- intstall react-icons
Closes: [ISSUE n.22 ](https://github.com/ilPhil/roomatch/issues/22)
> feat: #22-add-ads-card

- src/Pages/Main/index.jsx
- src/Pages/Profile/Profile.module.scss
- src/Pages/Profile/index.jsx
- src/components/RoomAd/RoomAd.module.scss
- src/components/RoomAd/index.jsx
- src/components/SubscribeForm/RegistrationForm.jsx
- src/store/actions.js
add user page
Closes: [ISSUE n. 41 ]
https://github.com/ilPhil/roomatch/issues/41
> feat: add user page

- src/Pages/Profile/Profile.module.scss
- src/Pages/Profile/index.jsx
- src/components/RoomAd/RoomAd.module.scss
- src/components/RoomAd/index.jsx
- src/components/RoomCard/RoomCard.jsx
- src/components/RoomCard/RoomCard.module.scss
- src/libs/variables.scss
Questa PR:
- add info for the room card in main
- add first step for slider (as of now the component is hidden in its wrapper)
Closes: [ISSUE n.35 ](https://github.com/ilPhil/roomatch/issues/35)
> feat: #35-add-info-room-card

- src/Pages/Matches/index.jsx
- src/components/MatchesProfiles/MatchesProfiles.module.scss
- src/components/MatchesProfiles/index.jsx
Questa PR:
- Add static matches component to its page
Closes: [ISSUE n. 59 ](https://github.com/ilPhil/roomatch/issues/59)
> feat: add matches component

- src/Pages/Profile/index.jsx
- src/components/HeaderForms/HeaderForms.module.scss
- src/components/LoginForm/index.jsx
- src/components/RegistrationForm/registrationSteps/SecondStep.jsx
- src/components/RegistrationForm/registrationSteps/ThirdStep.jsx
- src/store/actions.js
fix: 
- login redirect
- registration redirect
- gender value in registration form
- lgbtq button fix
Closes: [ISSUE n. 58 ]
https://github.com/ilPhil/roomatch/issues/58
> fix: login and registration redirect and reg form

- src/Pages/Main/index.jsx
- src/Pages/Users/Users.module.scss
- src/Pages/Users/index.jsx
- src/components/RoomAd/RoomAd.module.scss
- src/components/RoomAd/index.jsx
- src/components/UserCard/UserCard.module.scss
- src/components/UserCard/index.jsx
- src/store/actions.js
add users page list from profile page to find new roommates
Closes: [ISSUE n.68 ](https://github.com/ilPhil/roomatch/issues/68)
> feat: add users page list

- package-lock.json
- package.json
- src/Pages/Likes/index.jsx
- src/Pages/Main/index.jsx
- src/Pages/RoomDetails/RoomDetails.module.scss
- src/Pages/RoomDetails/index.jsx
- src/Pages/Rooms/index.jsx
- src/components/LikesCard/index.jsx
- src/components/PhotoGallery/PhotoGallery.module.scss
- src/components/PhotoGallery/index.jsx
- src/components/RoomAd/RoomAd.module.scss
- src/components/RoomAd/index.jsx
- src/components/RoomCard/RoomCard.jsx
add room details page and photgallery component
Closes: [ISSUE n. 56-72 ]
https://github.com/ilPhil/roomatch/issues/56
https://github.com/ilPhil/roomatch/issues/72
> feat: add rooms details and photogallery components

- src/components/MainNav/MainNav.module.scss
Fix main menu position
Closes: [ISSUE n. 61]
https://github.com/ilPhil/roomatch/issues/61
> fix: menu position

- src/components/PhotoGallery/PhotoGallery.module.scss
fix photogallery images size to square shape
> fix: photogallery img size

- src/components/RegistrationForm/index.jsx
- src/components/RegistrationForm/registrationSteps/SecondStep.jsx
> fix: gender value in registration form

- src/components/RoomCard/RoomCard.jsx
- src/components/UserCard/index.jsx
fix like and displike function with new backend functions
> fix: like displike with new be

- src/components/LikesCardInfo/index.jsx
- src/components/RoomCard/RoomCard.jsx
- src/components/RoomCard/RoomCard.module.scss
Questa PR:
- aggiunge feature ...
- fixes ...
Closes: [ISSUE n. 96 ](https://github.com/ilPhil/roomatch/issues/96)
> fix SCSS Room cards

- src/components/LoginForm/LoginForm.module.scss
- src/components/LoginForm/index.jsx
- src/store/actions.js
handle http errors in login 
Closes: [ISSUE n. 100](https://github.com/ilPhil/roomatch/issues/100)
> feat: display message to wrong login

- src/components/AddRoomAdForm/AddRoomAdForm.module.scss
- src/components/AddRoomAdForm/adsSteps/FirstStepForm.jsx
- src/components/AddRoomAdForm/adsSteps/FirstStepForm.module.scss
- src/components/AddRoomAdForm/adsSteps/SecondStepForm.jsx
- src/components/AddRoomAdForm/adsSteps/SecondStepForm.module.scss
- src/components/AddRoomAdForm/adsSteps/ThirdStepForm.jsx
- src/components/AddRoomAdForm/adsSteps/ThirdStepForm.module.scss
- src/components/AddRoomAdForm/index.jsx
- src/components/HeaderAddRoomAdForm/HeaderAddRoomForm.jsx
- src/components/HeaderAddRoomAdForm/HeaderAddRoomForm.module.scss
room form completed
Closes: [ISSUE n. 98 ](https://github.com/ilPhil/roomatch/issues/98)
> feat: add room form

- src/components/RegistrationForm/registrationSteps/ThirdStep.jsx
- src/components/RegistrationForm/registrationSteps/ThirdStep.module.scss
add message to registration form if an user already exist
Closes: [ISSUE n. 110](https://github.com/ilPhil/roomatch/issues/110)
> feat: error message if an usr already exist

- src/Pages/Likes/Likes.module.scss
- src/Pages/Likes/index.jsx
- src/Pages/RoomDetails/RoomDetails.module.scss
- src/Pages/RoomDetails/index.jsx
- src/Pages/Users/Users.module.scss
- src/components/LikesCard/LikesCard.module.scss
- src/components/LikesCard/index.jsx
- src/components/LikesCardInfo/LikesCardInfo.module.scss
- src/components/LikesCardInfo/index.jsx
- src/components/MainNav/MainNav.module.scss
- src/components/PhotoGallery/PhotoGallery.module.scss
- src/components/UserCard/UserCard.module.scss
- src/components/UserCard/index.jsx
Questa PR:
- fix responsive design
Closes: [ISSUE n.107](https://github.com/ilPhil/roomatch/issues/107)
> refactor: fix and implement responsive design

- src/components/RegistrationForm/registrationSteps/ThirdStep.jsx
fix login for new users
Closes: [ISSUE n. 118](https://github.com/ilPhil/roomatch/issues/118)
> fix deploy

- src/Pages/Matches/Matches.module.scss
- src/Pages/Matches/index.jsx
- src/components/MatchesProfiles/MatchesProfiles.module.scss
- src/components/MessagePreview/MessagePreview.module.scss
- src/components/MessagePreview/index.jsx
Questa PR:
- create messagePreview component
- add it to match page
Closes: [ISSUE n. 109 ](https://github.com/ilPhil/roomatch/issues/109)
> #109-add-contennt-to-match-page

- src/components/AddRoomAdForm/adsSteps/ThirdStepForm.jsx
- src/components/RoomAd/index.jsx
- src/store/actions.js
add remove room btn and develope backend logic
> fix: add remove room

- src/Pages/Matches/Matches.module.scss
- src/Pages/Profile/index.jsx
- src/Pages/RoomDetails/RoomDetails.module.scss
- src/Pages/RoomDetails/index.jsx
- src/components/AddRoomAdForm/adsSteps/FirstStepForm.jsx
- src/components/AddRoomAdForm/adsSteps/SecondStepForm.jsx
- src/components/AddRoomAdForm/adsSteps/ThirdStepForm.jsx
- src/components/AddRoomAdForm/index.jsx
- src/components/MatchesProfiles/MatchesProfiles.module.scss
Questa PR:
- add details room to room details page
Closes: [ISSUE n. 124 ](https://github.com/ilPhil/roomatch/issues/124)
> #124 add room details in room details page

- src/Pages/Main/index.jsx
- src/Pages/Matches/index.jsx
- src/Pages/Messages/Messages.module.scss
- src/Pages/Messages/index.jsx
- src/components/MainNav/MainNav.module.scss
- src/components/MainNav/index.jsx
- src/components/MatchesProfiles/MatchesProfiles.module.scss
- src/components/MatchesProfiles/index.jsx
- src/components/MessagePreview/MessagePreview.module.scss
- src/components/MessagePreview/index.jsx
- Add matches logic
- Add notifies
- Add messages preview with link to chat page
Closes: [ISSUE n. 65 ](https://github.com/ilPhil/roomatch/issues/65)
Closes: [ISSUE n. 127 ](https://github.com/ilPhil/roomatch/issues/127)
Closes: [ISSUE n. 128 ](https://github.com/ilPhil/roomatch/issues/128)
> feat: add notifies, messages preview, match preview

- src/Pages/Likes/index.jsx
- src/components/LikesCard/LikesCard.module.scss
- src/components/LikesCard/index.jsx
- src/components/MatchesProfiles/index.jsx
issue: 134 (https://github.com/ilPhil/roomatch/issues/134)
> Feat: add likes notifies in likes page

- src/Pages/Main/index.jsx
- src/Pages/Matches/index.jsx
- src/Pages/Messages/Messages.module.scss
- src/Pages/Messages/index.jsx
- src/Pages/RoomDetails/index.jsx
- src/Pages/UserDetails/UserDetails.module.scss
- src/Pages/UserDetails/index.jsx
- src/components/ChatContainer/ChatContainer.module.scss
- src/components/ChatContainer/index.jsx
- src/components/ChatForm/ChatForm.module.scss
- src/components/ChatForm/index.jsx
- src/components/ChatHeader/ChatHeader.module.scss
- src/components/ChatHeader/index.jsx
- src/components/MatchesProfiles/index.jsx
- src/components/MessagePreview/index.jsx
- src/components/RoomAd/index.jsx
- src/store/actions.js
Questa PR:
- add messages/chat page
- add user details page
Closes: [ISSUE n. 136 ](https://github.com/ilPhil/roomatch/issues/136)
Closes: [ISSUE n. 143 ](https://github.com/ilPhil/roomatch/issues/143)
> Feat: add chat page

- src/Pages/Rooms/index.jsx
- src/Pages/Users/index.jsx
- src/components/RoomCard/RoomCard.jsx
- src/components/UserCard/index.jsx
add compatibility to user and room card 
Closes: [ISSUE n. 130 ](https://github.com/ilPhil/roomatch/issues/130)
> Feat: add compatibility to user and room card

- src/Pages/Users/Users.module.scss
- src/components/RoomCard/RoomCard.jsx
- src/components/RoomCard/RoomCard.module.scss
- src/components/UserCard/UserCard.module.scss
- src/components/UserCard/index.jsx
Questa PR:
- fix style third step add room form
- add slide to user card > user card info
Closes: [ISSUE n. 113 ](https://github.com/ilPhil/roomatch/issues/113)
> feat: #113 add slide to user card - user info

- src/components/AddRoomAdForm/adsSteps/SecondStepForm.jsx
- src/components/AddRoomAdForm/adsSteps/SecondStepForm.module.scss
- src/components/AddRoomAdForm/adsSteps/ThirdStepForm.jsx
- src/components/AddRoomAdForm/adsSteps/ThirdStepForm.module.scss
Questa PR:
- fix style of second and third steps add room form
- fix little bug for "address" 
Closes: [ISSUE n.147](https://github.com/ilPhil/roomatch/issues/147)
> fix: #147 fix form add room

- src/Pages/Messages/index.jsx
- src/Pages/Rooms/Rooms.module.scss
- src/Pages/Rooms/index.jsx
- src/components/ChatForm/index.jsx
- src/components/ChatHeader/index.jsx
- src/components/CitiesFilter/CitiesFilter.module.scss
- src/components/CitiesFilter/index.jsx
- src/components/MatchesProfiles/index.jsx
- src/components/MessagePreview/index.jsx
fix messages
Closes: [ISSUE n.150 ](https://github.com/ilPhil/roomatch/issues/150)
> fix: messages

- src/Pages/Matches/index.jsx
- src/Pages/Messages/index.jsx
- src/Pages/Rooms/index.jsx
- src/components/MainNav/index.jsx
- src/components/MatchesProfiles/index.jsx
- src/components/MessagePreview/index.jsx
- add notifies for new messages
- delete notification after to read message
- order messages by date
Closes: [ISSUE n. 154 ](https://github.com/ilPhil/roomatch/issues/154)
> feat: add new message notifications and read notif

- src/Pages/Messages/Messages.module.scss
- src/Pages/Messages/index.jsx
- src/Pages/Profile/Profile.module.scss
- src/Pages/Profile/index.jsx
- src/Pages/RoomDetails/RoomDetails.module.scss
- src/components/ChatContainer/ChatContainer.module.scss
- src/components/ChatContainer/index.jsx
- src/components/ChatForm/ChatForm.module.scss
- src/components/ChatForm/index.jsx
- src/components/ChatHeader/ChatHeader.module.scss
- src/components/ChatHeader/index.jsx
- src/components/MessagePreview/MessagePreview.module.scss
- src/components/PhotoGallery/PhotoGallery.module.scss
- src/components/UserCard/UserCard.module.scss
Questa PR:
- add style to chat
- fix cursor 
- add style to scrollbar in Photogallery
Closes: [ISSUE n.156 ](https://github.com/ilPhil/roomatch/issues/156)
> feat: #156 add style to chat

- src/components/CitiesFilter/CitiesFilter.module.scss
- src/components/LikesCardInfo/LikesCardInfo.module.scss
- src/components/LoginForm/LoginForm.module.scss
- src/components/RoomCard/RoomCard.module.scss
- src/components/UserCard/UserCard.module.scss
Add cursor pointer when needed.
Closes: [ISSUE n. 159 ](https://github.com/ilPhil/roomatch/issues/159)
> fix: cursor pointer

- src/Pages/Matches/Matches.module.scss
- src/Pages/Matches/index.jsx
> fix margin text

- src/Pages/NewRoom/NewRoom.module.scss
- src/Pages/Rooms/Rooms.module.scss
- src/Pages/Rooms/index.jsx
- src/Pages/Users/Users.module.scss
- src/Pages/Users/index.jsx
- src/components/AddRoomAdForm/adsSteps/SecondStepForm.jsx
- src/components/AddRoomAdForm/adsSteps/SecondStepForm.module.scss
- src/components/AddRoomAdForm/adsSteps/ThirdStepForm.module.scss
- src/libs/http.js
- add errors handlings
- fix third step add room form
Closes: [ISSUE n. 163](https://github.com/ilPhil/roomatch/issues/163)
Closes: [ISSUE n. 192](https://github.com/ilPhil/roomatch/issues/192)
Perfavore elimina le optizioni che non sono rilevanti.
> add http errors and fix some css

- src/components/UserCard/index.jsx
Fix data rendering in User cards list
> fix: user data in card

- src/Pages/Messages/index.jsx
- src/Pages/Profile/Profile.module.scss
- src/Pages/Rooms/index.jsx
- src/Pages/Users/index.jsx
- src/components/ChatContainer/index.jsx
fix too many request to backend
Closes: [ISSUE n. 227](https://github.com/ilPhil/roomatch/issues/227)
> fix: too many call to backend

- src/components/AddRoomAdForm/adsSteps/FirstStepForm.jsx
- src/components/AddRoomAdForm/index.jsx
- src/components/CitiesSelector/index.jsx
- src/components/EditRoomAdForm/adsSteps/FirstStepForm.jsx
- src/components/EditRoomAdForm/adsSteps/ThirdStepForm.jsx
- src/components/EditRoomAdForm/index.jsx
- src/components/RegistrationForm/index.jsx
- src/components/RegistrationForm/registrationSteps/SecondStep.jsx
fix cities selector 
Closes: [ISSUE n. 225 ](https://github.com/ilPhil/roomatch/issues/225)
> fix: cities selector

- src/Pages/Likes/index.jsx
- src/components/MatchesProfiles/index.jsx
fix likes and match order position
Closes: [ISSUE n. 226](https://github.com/ilPhil/roomatch/issues/226)
> Fix: likes and match order

- src/Pages/Main/index.jsx
- src/Pages/Profile/index.jsx
add scroll top top when change page
Closes: [ISSUE n. 222](https://github.com/ilPhil/roomatch/issues/222)
> Feat: scoll on top

- src/App.js
- src/Pages/Login/index.jsx
- src/Pages/Main/index.jsx
- src/Pages/Registration/index.jsx
- src/components/LoginForm/LoginForm.module.scss
- src/components/LoginForm/index.jsx
- src/components/RegistrationForm/index.jsx
- src/components/RegistrationForm/registrationSteps/ThirdStep.jsx
add registration redirect with message
Closes: [ISSUE n. 220](https://github.com/ilPhil/roomatch/issues/220)
> feat: registration redirect

- src/components/LoginForm/index.jsx
- src/components/RegistrationForm/registrationSteps/ThirdStep.jsx
- src/libs/functions.js
- add control to login input to lowercase
- capitalize name and surname first letter in registration
- send email in lowercase 
Closes: [ISSUE n. 239 ](https://github.com/ilPhil/roomatch/issues/239)
> feat: control to lowercase and uppercase to forms

- src/components/LikesCard/LikesCard.module.scss
Fix like card size for mobile screens.
Closes: [ISSUE n. 237 ](https://github.com/ilPhil/roomatch/issues/237)
> fix: fix like card size for mobile screens

- src/Pages/Likes/Likes.module.scss
- src/Pages/Likes/index.jsx
- src/Pages/Matches/Matches.module.scss
- src/Pages/Profile/Profile.module.scss
- src/Pages/RoomDetails/RoomDetails.module.scss
- src/Pages/RoomDetails/index.jsx
- src/Pages/Rooms/index.jsx
- src/Pages/UserDetails/UserDetails.module.scss
- src/Pages/UserDetails/index.jsx
- src/Pages/Users/Users.module.scss
- src/Pages/Users/index.jsx
- src/components/EditProfile/EditProfile.module.scss
- src/components/Footer/Footer.jsx
- src/components/HeaderForms/HeaderForms.module.scss
- src/components/LikesCardInfo/index.jsx
- src/components/PlaceHolder/PlaceHolder.module.scss
- src/components/RoomAd/RoomAd.module.scss
- src/components/RoomAd/index.jsx
- src/components/RoomCard/RoomCard.module.scss
- src/components/UserCard/UserCard.module.scss
- src/index.scss
Questa PR:
- fix css fonts and border
> fix:css font border

- src/components/LikesCardInfo/LikesCardInfo.module.scss
- src/components/LikesCardInfo/index.jsx
Closes: [ISSUE n. 245](https://github.com/ilPhil/roomatch/issues/245)
> Feat: add comp bar to likes card
